const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {unzipSync} from 'fflate';
fs.mkdirSync('test-output',{recursive:true});
const root=path.resolve('dist'),server=http.createServer((req,res)=>{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'js':'text/javascript','mjs':'text/javascript','css':'text/css','html':'text/html','wasm':'application/wasm','json':'application/json','jpg':'image/jpeg'})[p.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu'],headless:true});try{
const p=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];p.setDefaultTimeout(15000);p.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForSelector('#floorList',{state:'attached'});
await p.locator('#datasetFile').setInputFiles(path.join(root,'data/prueba-cad.dxf'));await p.waitForFunction(()=>document.querySelector('#cadStatus').textContent.includes('trazos'));assert.match(await p.locator('#cadStatus').textContent(),/trazos/);
const d={schema:'archglancer/1',name:'Dos pisos de prueba',objects:[{id:'pb',space:'Modelo',layer:'Muros',points:[[0,0],[8,0],[8,8],[0,8],[0,0]]},{id:'p1',space:'Modelo',layer:'Muros',points:[[100,0],[108,0],[108,8],[100,8],[100,0]]}],views:[{name:'Planta baja',space:'Modelo',bounds:[-1,-1,9,9]},{name:'Piso 1',space:'Modelo',bounds:[99,-1,109,9]}]};
await p.locator('#datasetFile').setInputFiles({name:'pisos.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await p.waitForFunction(()=>document.querySelectorAll('.floor-row').length===2);await p.screenshot({path:'test-output/cad.png',fullPage:true});
await p.locator('.floor-row select').first().selectOption('piso');
await p.locator('.floor-row input[placeholder]').first().fill('Revisado para prueba');await p.locator('.floor-row input[placeholder]').first().dispatchEvent('change');
await p.locator('.floor-row').first().getByRole('button',{name:'↓',exact:true}).click();
assert.equal(await p.locator('.floor-row input[aria-label="Nombre del piso o vista"]').first().inputValue(),'Piso 1');
await p.locator('#rendersTab').click();await p.locator('#renderRestore').click();await p.locator('#renderFloor').selectOption({label:'Planta baja'});const linkedId=await p.locator('#renderFloor').inputValue();assert.ok(linkedId);await p.locator('#renderGoFloor').click();
await p.locator('#floorAll').click();await p.locator('#pdfPaper').selectOption('A4');await p.locator('#pdfOrientation').selectOption('portrait');await p.locator('#pdfUnits').selectOption('1000');await p.locator('#pdfDrawingScale').selectOption('100');
await p.locator('#makePdf').click();await p.waitForFunction(()=>document.querySelector('#projectStatus').textContent.includes('PDF generado'),{timeout:30000});console.log('PDF rendered');assert.equal(await p.locator('#pdfCount').textContent(),'/ 3');await p.screenshot({path:'test-output/pdf.png',fullPage:true});
await p.locator('#pdfNext').click();await p.waitForFunction(()=>document.querySelector('#pdfPage').value==='2');
await p.locator('#cadTab').click();let dl=p.waitForEvent('download');await p.locator('#floorZip').click();const zipDl=await dl;console.log('floor zip downloaded');const zip=unzipSync(fs.readFileSync(await zipDl.path()));assert.equal(Object.keys(zip).filter(n=>n.endsWith('.pdf')).length,2);
dl=p.waitForEvent('download');await p.locator('#saveProject').click();const project=await dl;console.log('project downloaded');await project.saveAs('test-output/roundtrip.zip');await p.locator('#projectFile').setInputFiles(path.resolve('test-output/roundtrip.zip'));await p.waitForFunction(()=>/restaurado|No se completó/.test(document.querySelector('#projectStatus').textContent));console.log('RESTORE',await p.locator('#projectStatus').textContent());assert.match(await p.locator('#projectStatus').textContent(),/restaurado/);assert.equal(await p.locator('.floor-row').count(),2);
assert.equal(await p.locator('#pdfOrientation').inputValue(),'portrait');assert.equal(await p.locator('#pdfDrawingScale').inputValue(),'100');
assert.equal(await p.locator('.floor-row select').nth(1).inputValue(),'piso');assert.equal(await p.locator('.floor-row input[placeholder]').nth(1).inputValue(),'Revisado para prueba');
await p.locator('#rendersTab').click();assert.equal(await p.locator('#renderFloor').inputValue(),linkedId);await p.locator('#renderGoFloor').click();

await p.locator('.floor-row button').first().click();await p.locator('#floorCrop').click();await p.locator('#cadCanvas').scrollIntoViewIfNeeded();const bb=await p.locator('#cadCanvas').boundingBox();await p.mouse.move(bb.x+bb.width*.3,bb.y+bb.height*.3);await p.mouse.down();await p.mouse.move(bb.x+bb.width*.7,bb.y+bb.height*.7);await p.mouse.up();assert.equal(await p.locator('.floor-row').count(),3);
await p.locator('#datasetFile').setInputFiles({name:'bad.dxf',mimeType:'text/plain',buffer:Buffer.from('invalid')});await p.waitForFunction(()=>document.querySelector('#cadStatus').textContent.includes('No se cargó'));assert.equal(await p.locator('.floor-row').count(),3);
// Load another arbitrary project: images and prior PDF must not leak into it.
const other={schema:'archglancer/1',name:'Independent facility',units:'ft',objects:[{id:'x',layer:'CUSTOM-X',space:'Sheet Omega',points:[[0,0],[20,0],[20,10],[0,10],[0,0]]}]};
await p.locator('#datasetFile').setInputFiles({name:'other.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(other))});await p.waitForFunction(()=>document.querySelector('#projectName').value==='Independent facility');
assert.equal(await p.locator('.floor-row').count(),1);assert.equal(await p.locator('#pdfUnits').inputValue(),'304.8');assert.equal(await p.evaluate(()=>window.archRenders.snapshot().length),0);assert.equal(await p.locator('#pdfDownload').isHidden(),true);
await p.locator('#hideLayers').click();dl=p.waitForEvent('download');await p.locator('#saveProject').click();const emptyProject=await dl;const emptyPath=await emptyProject.path();const emptyFiles=unzipSync(fs.readFileSync(emptyPath));assert.equal(JSON.parse(Buffer.from(emptyFiles['project.json']).toString()).renders.length,0);
await p.locator('#showLayers').click();await p.locator('#projectFile').setInputFiles(emptyPath);await p.waitForFunction(()=>document.querySelector('#projectStatus').textContent.includes('restaurado'));assert.equal(await p.evaluate(()=>window.archCad.snapshot().visible.length),0);assert.equal(await p.evaluate(()=>window.archRenders.snapshot().length),0);
await p.locator('#showLayers').click();await p.locator('#floorAll').click();await p.locator('#makePdf').click();await p.waitForFunction(()=>document.querySelector('#projectStatus').textContent.includes('PDF generado'));assert.equal(await p.locator('#pdfCount').textContent(),'/ 2');await p.locator('#cadTab').click();
await p.setViewportSize({width:390,height:844});await p.screenshot({path:'test-output/mobile.png',fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'mobile overflow');assert.deepEqual(errors,[]);console.log('PASS real Chromium: DXF worker, 2 floors, 3-page PDF viewer, per-floor ZIP, project restoration, manual crop, invalid DXF, mobile width, view order/type/notes, render links and print settings roundtrip; no JS errors');
}finally{await browser.close();server.close();}
