import {compatibility,UNIT_MM} from './project-analysis.mjs';
import {setupFloorSheets} from './floor-sheets.mjs';
import * as pdfjs from 'pdfjs-dist/build/pdf.mjs';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
import {exportCadPDF} from './pdf-export.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='pdf-engine/pdf.worker.mjs';
const $=id=>document.getElementById(id);
const bar=document.createElement('section');bar.className='project-bar';
bar.innerHTML=`<label>Proyecto <input id="projectName" value="Mi proyecto" maxlength="100"></label><button class="tool-button" id="saveProject">Guardar proyecto ZIP</button><button class="tool-button" id="openProject">Abrir proyecto ZIP</button><input type="file" hidden id="projectFile" accept=".zip"><button class="tool-button" id="openPdf">Abrir PDF</button><input type="file" hidden id="pdfFile" accept=".pdf"><button class="tool-button" id="pdfView">Ver PDF</button><button class="tool-button" id="cancelExport" hidden>Cancelar exportación</button><span id="projectStatus" role="status">Archivos locales · guarda un ZIP para conservar tu trabajo.</span>`;
document.querySelector('.topbar').after(bar);
const root=document.createElement('main');root.id='documentWorkspace';root.hidden=true;root.className='document-workspace';
root.innerHTML=`<div class="pdf-controls"><button class="tool-button" id="pdfPrev">←</button><label>Página <input type="number" id="pdfPage" min="1" value="1"></label><span id="pdfCount"></span><button class="tool-button" id="pdfNext">→</button><button class="tool-button" id="pdfMinus">−</button><output id="pdfScale">100 %</output><button class="tool-button" id="pdfPlus">+</button><button class="tool-button" id="pdfFit">Ajustar</button><a class="tool-button" id="pdfDownload" hidden>Descargar PDF</a></div><p id="pdfStatus" role="status">Abre un PDF o genéralo desde Datasets CAD.</p><div class="pdf-scroll"><canvas id="documentCanvas"></canvas></div>`;
document.querySelector('.shell').append(root);
const exportBar=document.createElement('div');exportBar.className='pdf-controls';exportBar.innerHTML=`<label>Papel <select id="pdfPaper"><option>A3</option><option>A4</option><option>A2</option><option>A1</option></select></label><label>Orientación <select id="pdfOrientation"><option value="landscape">Horizontal</option><option value="portrait">Vertical</option></select></label><label>Unidades CAD <select id="pdfUnits"><option value="unknown">Sin definir</option><option value="1">Milímetros</option><option value="10">Centímetros</option><option value="1000">Metros</option><option value="25.4">Pulgadas</option><option value="304.8">Pies</option><option value="1000000">Kilómetros</option><option value="0.001">Micrómetros</option><option value="0.000001">Nanómetros</option></select></label><label>Escala <select id="pdfDrawingScale"><option value="fit">Ajustar a hoja</option><option value="50">1:50</option><option value="100">1:100</option><option value="200">1:200</option><option value="500">1:500</option></select></label><label>Trazo <select id="pdfLineWidth"><option value="0.4">0.14 mm</option><option value="0.71">0.25 mm</option><option value="0.99">0.35 mm</option></select></label><label>Contenido <select id="pdfScope"><option value="floors">Pisos/vistas seleccionados</option><option value="current">Vista CAD actual</option></select></label><button class="tool-button" id="makePdf">Generar PDF de pisos</button><button class="tool-button" id="floorZip">PDF por piso (ZIP)</button><span>Capas visibles · PDF vectorial · incluye informe</span>`;
$('cadWorkspace').querySelector('.cad-main').prepend(exportBar);
const selectedFloors=setupFloorSheets();
let pdf=null,pdfTask=null,pdfFile=null,pdfUrl=null,pageNo=1,zoom=1,renderTask=null,renderGeneration=0,loadGeneration=0,busy=false;let exportAbort=null;
function status(s){$('projectStatus').textContent=s;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
for(const id of ['cadTab','pdfTab','rendersTab']){const old=$(id).onclick;$(id).onclick=()=>{root.hidden=true;$('pdfView').setAttribute('aria-pressed','false');old();};}
function showPdf(){for(const selector of ['#cadWorkspace','#renderWorkspace','.workspace','.rail'])document.querySelector(selector).hidden=true;for(const id of ['cadTab','pdfTab','rendersTab'])$(id).setAttribute('aria-pressed','false');root.hidden=false;$('pdfView').setAttribute('aria-pressed','true');}
$('pdfView').onclick=showPdf;$('pdfTab').onclick=showPdf;
async function render(){if(!pdf)return;const ticket=++renderGeneration;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}renderTask=null;}try{
 const page=await pdf.getPage(pageNo);if(ticket!==renderGeneration)return;
 const base=page.getViewport({scale:zoom}),ratio=Math.min(window.devicePixelRatio||1,2),effective=Math.min(ratio,Math.sqrt(16000000/(base.width*base.height))),vp=page.getViewport({scale:zoom*effective}),canvas=$('documentCanvas');
 canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);canvas.style.width=base.width+'px';canvas.style.height=base.height+'px';
 $('pdfPage').value=pageNo;$('pdfPage').max=pdf.numPages;$('pdfCount').textContent='/ '+pdf.numPages;$('pdfScale').textContent=Math.round(zoom*100)+' %';$('pdfPrev').disabled=pageNo===1;$('pdfNext').disabled=pageNo===pdf.numPages;
 $('pdfStatus').textContent='Dibujando página '+pageNo+'…';renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport:vp});await renderTask.promise;if(ticket===renderGeneration)$('pdfStatus').textContent=pdfFile.name+' · '+(effective<ratio?'Resolución limitada para proteger la memoria.':'PDF original; sin reconstrucción CAD ni OCR.');
 }catch(e){if(e.name!=='RenderingCancelledException')$('pdfStatus').textContent='No se pudo mostrar: '+e.message;}}
async function fitPdf(){if(!pdf)return;const doc=pdf,p=await doc.getPage(pageNo);if(doc!==pdf)return;const v=p.getViewport({scale:1});zoom=Math.max(.05,Math.min(3,(root.clientWidth-60)/v.width,(window.innerHeight*.65)/v.height));await render();}
async function loadPdf(file){if(!file||file.size>100*1024*1024)throw Error('PDF: límite de 100 MB.');const ticket=++loadGeneration;status('Abriendo PDF…');const nextTask=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,cMapUrl:'pdf-engine/cmaps/',cMapPacked:true,standardFontDataUrl:'pdf-engine/standard_fonts/',wasmUrl:'pdf-engine/wasm/'});let next;try{next=await nextTask.promise;}catch(e){await nextTask.destroy();throw e;}
 if(ticket!==loadGeneration){await nextTask.destroy();return;}renderGeneration++;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}renderTask=null;}if(pdfTask)await pdfTask.destroy();if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdf=next;pdfTask=nextTask;pdfFile=file;pageNo=1;pdfUrl=URL.createObjectURL(file);$('pdfDownload').href=pdfUrl;$('pdfDownload').download=file.name;$('pdfDownload').hidden=false;showPdf();await fitPdf();status('PDF abierto: '+file.name);}
$('cancelExport').onclick=()=>exportAbort?.abort();
async function pdfExport(snap,options){exportAbort=new AbortController();$('cancelExport').hidden=false;try{return await exportCadPDF(snap,{...options,orientation:$('pdfOrientation').value,unitMM:Number($('pdfUnits').value)||null,scaleDenominator:$('pdfDrawingScale').value==='fit'?null:Number($('pdfDrawingScale').value),lineWidth:Number($('pdfLineWidth').value),signal:exportAbort.signal});}finally{$('cancelExport').hidden=true;exportAbort=null;}}
async function action(fn){if(busy){status('Espera a que termine la operación actual.');return;}busy=true;for(const id of ['saveProject','openProject','makePdf','openPdf','floorZip','openCad','loadDwg','renderOpen','renderRestore'])$(id).disabled=true;try{await fn();}catch(e){status('No se completó: '+e.message);}finally{busy=false;for(const id of ['saveProject','openProject','makePdf','openPdf','floorZip','openCad','loadDwg','renderOpen','renderRestore'])$(id).disabled=false;}}
$('openPdf').onclick=()=>$('pdfFile').click();$('pdfFile').onchange=e=>{const file=e.target.files[0];e.target.value='';if(file)action(()=>loadPdf(file));};
$('pdfPrev').onclick=()=>{if(pdf&&pageNo>1){pageNo--;render();}};$('pdfNext').onclick=()=>{if(pdf&&pageNo<pdf.numPages){pageNo++;render();}};
$('pdfPage').onchange=e=>{if(pdf){pageNo=Math.max(1,Math.min(pdf.numPages,Math.floor(Number(e.target.value)||1)));render();}};
$('pdfPlus').onclick=()=>{zoom=Math.min(8,zoom*1.25);render();};$('pdfMinus').onclick=()=>{zoom=Math.max(.05,zoom/1.25);render();};$('pdfFit').onclick=fitPdf;
$('makePdf').onclick=()=>action(async()=>{const bytes=await pdfExport(window.archCad.snapshot(),{selectedViews:$('pdfScope').value==='floors'?selectedFloors():null,paper:$('pdfPaper').value,progress:status});await loadPdf(new File([bytes],'plano-archglancer.pdf',{type:'application/pdf'}));status('PDF generado. Incluye un informe de omisiones al final.');});
$('saveProject').onclick=()=>action(async()=>{
 selectedFloors();const cad=window.archCad.snapshot();if(!cad.data)throw Error('Espera a que termine de cargar el dibujo.');const renders=window.archRenders.snapshot(),manifest={schema:'archglancer-project/1',name:$('projectName').value,created:new Date().toISOString(),renders:[],cad:'cad.json',original:null,pdf:null,cadState:{visible:cad.visible,showText:cad.showText,view:cad.view},printSettings:Object.fromEntries(['pdfPaper','pdfOrientation','pdfUnits','pdfDrawingScale','pdfLineWidth'].map(id=>[id,$(id).value]))},files={'cad.json':strToU8(JSON.stringify(cad.data))};let bytes=files['cad.json'].length;
 const add=async(path,blob)=>{bytes+=blob.size;if(bytes>512*1024*1024)throw Error('Proyecto mayor a 512 MB; reduce las imágenes.');files[path]=new Uint8Array(await blob.arrayBuffer());};
 status('Preparando el proyecto…');for(let i=0;i<renders.length;i++){const item=renders[i],r=await fetch(item.src);if(!r.ok)throw Error('No se pudo conservar '+item.name);const path='renders/'+i+'.'+item.name.split('.').pop().toLowerCase();await add(path,await r.blob());manifest.renders.push({path,name:item.name,floorId:item.floorId||null});}
 if(cad.originalFile){manifest.original={path:'original/source.'+cad.originalFile.name.split('.').pop().toLowerCase(),name:cad.originalFile.name};await add(manifest.original.path,cad.originalFile);}
 if(pdfFile){manifest.pdf={path:'document.pdf',name:pdfFile.name};await add('document.pdf',pdfFile);}
 files['project.json']=strToU8(JSON.stringify(manifest));status('Comprimiendo proyecto…');await new Promise(r=>setTimeout(r,30));download(new Blob([zipSync(files,{level:0})],{type:'application/zip'}),($('projectName').value||'proyecto').replace(/[^a-zA-Z0-9_-]/g,'_')+'.archglancer.zip');status('Proyecto descargado. Conserva el ZIP para volver a abrirlo; no se guarda en un servidor.');
});
$('openProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=e=>{const file=e.target.files[0];e.target.value='';if(file)action(async()=>{
 if(file.size>520*1024*1024)throw Error('ZIP mayor a 520 MB.');status('Leyendo proyecto…');let total=0,count=0;
 const files=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:entry=>{total+=entry.originalSize;count++;if(total>512*1024*1024||count>110||entry.originalSize>300*1024*1024)throw Error('Proyecto demasiado grande o con demasiados archivos.');return true;}});
 if(!files['project.json'])throw Error('Este ZIP no es un proyecto guardado desde ArchGlancer. Si descargaste el código, extráelo en tu computadora y sigue README.md.');const manifest=JSON.parse(strFromU8(files['project.json']));if(manifest.schema!=='archglancer-project/1'||!Array.isArray(manifest.renders)||manifest.renders.length>100)throw Error('No es un proyecto ArchGlancer válido.');
 const data=JSON.parse(strFromU8(files[manifest.cad]||new Uint8Array()));window.archCad.validate(data);
 const get=(m,max)=>{if(!m||typeof m.name!=='string'||!files[m.path]||files[m.path].length>max*1024*1024)throw Error('Falta un archivo o excede el límite.');return new File([files[m.path]],m.name);};
 const images=manifest.renders.map(m=>{if(!/\.(jpe?g|png|webp)$/i.test(m.name))throw Error('Formato de imagen no compatible.');return get(m,32);});
 const original=manifest.original?get(manifest.original,300):null,documentFile=manifest.pdf?get(manifest.pdf,100):null;
 
 if(documentFile)await loadPdf(documentFile);else{loadGeneration++;renderGeneration++;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}renderTask=null;}if(pdfTask)await pdfTask.destroy();if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdf=null;pdfTask=null;pdfFile=null;pdfUrl=null;$('documentCanvas').width=0;$('pdfDownload').hidden=true;$('pdfStatus').textContent='Este proyecto no contiene un PDF.';$('pdfCount').textContent='';}
 window.archCad.restore(data,original);window.archCad.restoreState(manifest.cadState);window.archRenders.restore(images);window.archRenders.restoreLinks(manifest.renders);for(const [id,value] of Object.entries(manifest.printSettings||{})){if(['pdfPaper','pdfOrientation','pdfUnits','pdfDrawingScale','pdfLineWidth'].includes(id)&&[...$(id).options].some(o=>o.value===value))$(id).value=value;}$('projectName').value=String(manifest.name||'Proyecto').slice(0,100);$('cadTab').onclick();status('Proyecto restaurado. Capas, textos y vista recuperados cuando están guardados.');
 });};

$('helpButton').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();

$('floorZip').onclick=()=>action(async()=>{const views=selectedFloors();if(!views.length)throw Error('Selecciona o delimita al menos un piso.');const snap=window.archCad.snapshot(),files={};for(let i=0;i<views.length;i++){status('Generando piso '+(i+1)+' / '+views.length);files[String(i+1).padStart(2,'0')+'-'+views[i].name.replace(/[^a-zA-Z0-9_-]/g,'_')+'.pdf']=await pdfExport(snap,{selectedViews:[views[i]],includeReport:false,paper:$('pdfPaper').value,progress:status});}files['informe.txt']=strToU8(snap.report+'\nPDF obtenidos de geometría CAD recuperada. Papel '+$('pdfPaper').value+' / '+$('pdfOrientation').value+'; escala '+$('pdfDrawingScale').value+'; mm/unidad '+$('pdfUnits').value+'. Verifica unidades y medidas antes de imprimir. No se usan imágenes de PDF anteriores.\n'+views.map((v,i)=>(i+1)+'. '+v.name+' ['+(v.kind||'vista')+'] '+(v.notes||'')).join('\n'));download(new Blob([zipSync(files)],{type:'application/zip'}),'pisos-desde-cad.zip');status('Descargados '+views.length+' PDF, uno por piso/vista seleccionado.');});

const linkBar=document.createElement('div');linkBar.className='pdf-controls';
linkBar.innerHTML='<label>Asociar imagen a <select id="renderFloor"><option value="">Sin asociación</option></select></label><button class="tool-button" id="renderGoFloor">Ver vista en CAD</button><span id="renderLinkStatus" role="status"></span>';
$('renderCard').querySelector('.render-toolbar').after(linkBar);
function refreshLinks(){const select=$('renderFloor'),current=window.archRenders.current(),views=window.archCad.snapshot().data?.floorSheets||[];select.replaceChildren(new Option('Sin asociación',''));for(const v of views)select.add(new Option(v.name,v.id));select.value=current?.floorId||'';$('renderGoFloor').disabled=!views.some(v=>v.id===current?.floorId);$('renderLinkStatus').textContent=current?.floorId&&!select.value?'La vista asociada ya no existe. Elige otra.':'';}
$('renderFloor').onchange=()=>{window.archRenders.link($('renderFloor').value);refreshLinks();$('renderLinkStatus').textContent='Asociación actualizada. Guarda el proyecto ZIP para conservarla.';};
$('renderGoFloor').onclick=()=>{const v=window.archCad.snapshot().data?.floorSheets?.find(v=>v.id===$('renderFloor').value);if(v){$('cadTab').click();window.archCad.focusView(v);}};
for(const event of ['render-selected','floors-changed','cad-loaded'])window.addEventListener(event,refreshLinks);refreshLinks();

const diagnostic=document.createElement('section');diagnostic.className='panel';diagnostic.innerHTML='<h2>Compatibilidad del archivo</h2><p id="compatStatus">Carga un CAD para ver su diagnóstico.</p><button class="tool-button" id="downloadDiagnostic" disabled>Descargar diagnóstico JSON</button><p id="unitEvidence"></p>';
$('cadWorkspace').querySelector('.cad-side').prepend(diagnostic);
function analyzeCurrent(){const d=window.archCad.snapshot().data;if(!d)return;const c=compatibility(d);$('compatStatus').textContent=c.status+'. '+c.objects+' trazos, '+c.layers+' capas, '+c.spaces.length+' espacios, '+c.viewports+' ventanas. '+c.scope;$('downloadDiagnostic').disabled=false;$('unitEvidence').textContent='Unidades declaradas por el archivo: '+c.units+'. Confirma su correspondencia con una medida conocida.';}
$('downloadDiagnostic').onclick=()=>{const d=window.archCad.snapshot().data;if(d)download(new Blob([JSON.stringify(compatibility(d),null,2)],{type:'application/json'}),'diagnostico-cad.json');};
window.addEventListener('cad-loaded',e=>{const d=window.archCad.snapshot().data;analyzeCurrent();if(e.detail?.restoring)return;window.archRenders.clear();$('projectName').value=String(d.name||'Proyecto').replace(/\.[^.]+$/,'').slice(0,100);$('pdfUnits').value=String(UNIT_MM[d.units]||'unknown');$('pdfDrawingScale').value='fit';loadGeneration++;renderGeneration++;renderTask?.cancel();renderTask=null;const old=pdfTask;pdf=null;pdfTask=null;pdfFile=null;if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=null;if(old)old.destroy().catch(()=>{});$('documentCanvas').width=0;$('pdfDownload').hidden=true;$('pdfCount').textContent='';$('pdfStatus').textContent='Genera un PDF para este dibujo.';status('Nuevo dibujo cargado. Vistas pendientes de revisión; añade los renders de este proyecto.');});
analyzeCurrent();
const clearImages=document.createElement('button');clearImages.className='tool-button';clearImages.textContent='Quitar todas las imágenes';clearImages.onclick=()=>window.archRenders.clear();$('renderRestore').after(clearImages);
